#!/bin/bash
set -eo pipefail

git init evil-merge
cd evil-merge
echo Alice > alice.txt
echo Bob > bob.txt
echo lock > key.txt
git add ./*
git commit -m"At first, Alice and Bob are in the home"

git remote add origin git@github.com:aklaswad/where-is-carol.git
git branch -M main
git push -u -f origin main

murder=4
for i in {1..8} ; do
  git switch -c "branch-$i"
done

git switch main
echo "Carol" > carol.txt
echo "is mother" >> alice.txt
echo "is father" >> bob.txt

git add carol.txt
git add alice.txt
git add bob.txt
git commit -m"Carol was born."
git push -f origin main

for i in {1..8} ; do
  echo "New Lock" > key.txt
  git commit -a -m"Alice and Bob has changed the key"
  git switch "branch-$i"
  echo "A Key generated by branch $i, this might be conflicted." > key.txt
  echo "Implement feature $i" >> "feature$i.txt"
  git add "feature$i.txt"
  git commit -a -m "feat: Add feature $i"
  git push -f origin "branch-$i"
  git switch main
  git merge "branch-$i" || :
  echo "New key beyond $i" > key.txt
  git add key.txt
  if [ "$i" = "$murder" ]; then
    git rm carol.txt
  fi
  git commit -a -m"Merge branch 'branch-$i' into main"
  git push -f origin main
done

echo $murder